spring:
  rabbitmq:
    host: 192.168.9.131
    username: smallming
    password: smallming
custom:
  rabbitmq:
    queue:
      redis: redisQueue
      solr: solrQueue
      update: updateQueue
      createOrder: createOrderQueue